vnp_TmnCode=${VNP_TMN_CODE}
vnp_HashSecret=${VNP_HASH_SECRET}
vnp_PayUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp_ReturnUrl=http://localhost:8080/springserver/api/payment/vnpay-return
vnp_ApiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
